name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: Automation
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: Automation
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: Automation
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: Automation/playwright-report/
        retention-days: 30
  reports:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: Automation/report
