name: Playwright Tests

on:
  workflow_dispatch: # Trigger on workflow dispatch

jobs:
  test:
    runs-on: windows-latest # Run on Windows
    steps:
      - uses: actions/checkout@v4 # Use the latest version of the checkout action

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use the latest version of the setup-node action
        with:
          node-version: '18' # Use Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test test-environment/test-cases/team-courses/team-courses.test.js --reporter=html --config=playwright.config.js
