name: Playwright Tests

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test test-environment/test-cases/team-courses/team-courses.test.js --reporter=html

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ./test-results
        
    - name: Fetch artifact ID
      id: fetch-artifact-id
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          # Fetch the list of artifacts for the current run
          RESPONSE=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")

          # Output the response for debugging
          echo "API Response: $RESPONSE"
          
          # Extract artifact ID and URL
          ARTIFACT_ID=$(echo "$RESPONSE" | jq -r '.artifacts[] | select(.name == "playwright-report") | .id')

          if [ -z "$ARTIFACT_ID" ] || [ "$ARTIFACT_ID" == "null" ]; then
            echo "Artifact not found or no artifact with the expected name."
            exit 1
          fi

          # Use the artifact ID to get the download URL
          ARTIFACT_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip"

          # Output URL for debugging
          echo "Artifact URL: $ARTIFACT_URL"

          # Set the URL in environment variables
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV 
    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"GitHub Actions workflow completed. Number of failed tests: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{  env.ARTIFACT_ID }}."}' \
        https://hooks.slack.com/services/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

   
